services:
  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: docker-example-db
  database-admin:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: database
    depends_on:
      - db
  api:
    build: .
    restart: unless-stopped
    ports:
      - 5000:5000
    command: npm run dev
    depends_on:
      - db
    working_dir: /usr/src/docker-example
    volumes:
      - ./:/usr/src/docker-example
